/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Compatibility__factory } from "./IERC20Compatibility__factory";
export { ISoCashBankBackOffice__factory } from "./ISoCashBankBackOffice__factory";
export { ISoCashBankExternal__factory } from "./ISoCashBankExternal__factory";
export { ISoCashInterBank__factory } from "./ISoCashInterBank__factory";
