/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Compatibility } from "./IERC20Compatibility";
export type { ISoCashBankBackOffice } from "./ISoCashBankBackOffice";
export type { ISoCashBankExternal } from "./ISoCashBankExternal";
export type { ISoCashInterBank } from "./ISoCashInterBank";
