/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGreenBondMetadataInternal,
  IGreenBondMetadataInternalInterface,
} from "../../../../../contracts/register/green-payout/IGreenPayoutInternal.sol/IGreenBondMetadataInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "couponDate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reportURI",
        type: "string",
      },
    ],
    name: "GreenBondReportAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "greenBondURI",
        type: "string",
      },
    ],
    name: "GrendBondEmitted",
    type: "event",
  },
] as const;

export class IGreenBondMetadataInternal__factory {
  static readonly abi = _abi;
  static createInterface(): IGreenBondMetadataInternalInterface {
    return new Interface(_abi) as IGreenBondMetadataInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGreenBondMetadataInternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGreenBondMetadataInternal;
  }
}
