/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as htlcPaymentSol from "./htlc-payment.sol";
export type { htlcPaymentSol };
import type * as soCashAccountSol from "./so-cash-account.sol";
export type { soCashAccountSol };
import type * as soCashBankSol from "./so-cash-bank.sol";
export type { soCashBankSol };
import type * as whitelistedSendersSol from "./whitelisted-senders.sol";
export type { whitelistedSendersSol };
