/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as soCashAccountImplSol from "./so-cash-account-impl.sol";
export type { soCashAccountImplSol };
import type * as soCashBankImplSol from "./so-cash-bank-impl.sol";
export type { soCashBankImplSol };
