/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ibanSol from "./IBAN.sol";
export type { ibanSol };
import type * as htlcPaymentsSol from "./htlc-payments.sol";
export type { htlcPaymentsSol };
import type * as whitelistedSendersSol from "./whitelisted-senders.sol";
export type { whitelistedSendersSol };
