/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISoCashAccountFull__factory } from "./ISoCashAccountFull__factory";
export { ISoCashOwnedAccount__factory } from "./ISoCashOwnedAccount__factory";
