/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IGreenBondMetadataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "greenBondReports"
      | "greenBondURI"
      | "submitGreenBondReport"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GreenBondReportAdded" | "GrendBondEmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "greenBondReports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "greenBondURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitGreenBondReport",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "greenBondReports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "greenBondURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitGreenBondReport",
    data: BytesLike
  ): Result;
}

export namespace GreenBondReportAddedEvent {
  export type InputTuple = [couponDate: BigNumberish, reportURI: string];
  export type OutputTuple = [couponDate: bigint, reportURI: string];
  export interface OutputObject {
    couponDate: bigint;
    reportURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrendBondEmittedEvent {
  export type InputTuple = [greenBondURI: string];
  export type OutputTuple = [greenBondURI: string];
  export interface OutputObject {
    greenBondURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IGreenBondMetadata extends BaseContract {
  connect(runner?: ContractRunner | null): IGreenBondMetadata;
  waitForDeployment(): Promise<this>;

  interface: IGreenBondMetadataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  greenBondReports: TypedContractMethod<
    [couponDate_: BigNumberish],
    [string],
    "view"
  >;

  greenBondURI: TypedContractMethod<[], [string], "view">;

  submitGreenBondReport: TypedContractMethod<
    [couponDate_: BigNumberish, reportURI_: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "greenBondReports"
  ): TypedContractMethod<[couponDate_: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "greenBondURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitGreenBondReport"
  ): TypedContractMethod<
    [couponDate_: BigNumberish, reportURI_: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GreenBondReportAdded"
  ): TypedContractEvent<
    GreenBondReportAddedEvent.InputTuple,
    GreenBondReportAddedEvent.OutputTuple,
    GreenBondReportAddedEvent.OutputObject
  >;
  getEvent(
    key: "GrendBondEmitted"
  ): TypedContractEvent<
    GrendBondEmittedEvent.InputTuple,
    GrendBondEmittedEvent.OutputTuple,
    GrendBondEmittedEvent.OutputObject
  >;

  filters: {
    "GreenBondReportAdded(uint256,string)": TypedContractEvent<
      GreenBondReportAddedEvent.InputTuple,
      GreenBondReportAddedEvent.OutputTuple,
      GreenBondReportAddedEvent.OutputObject
    >;
    GreenBondReportAdded: TypedContractEvent<
      GreenBondReportAddedEvent.InputTuple,
      GreenBondReportAddedEvent.OutputTuple,
      GreenBondReportAddedEvent.OutputObject
    >;

    "GrendBondEmitted(string)": TypedContractEvent<
      GrendBondEmittedEvent.InputTuple,
      GrendBondEmittedEvent.OutputTuple,
      GrendBondEmittedEvent.OutputObject
    >;
    GrendBondEmitted: TypedContractEvent<
      GrendBondEmittedEvent.InputTuple,
      GrendBondEmittedEvent.OutputTuple,
      GrendBondEmittedEvent.OutputObject
    >;
  };
}
