/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOwnable__factory } from "./IOwnable__factory";
export { IWhitelistedSenders__factory } from "./IWhitelistedSenders__factory";
