/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGreenBondMetadata,
  IGreenBondMetadataInterface,
} from "../../../../../contracts/register/green-payout/IGreenPayout.sol/IGreenBondMetadata";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "couponDate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reportURI",
        type: "string",
      },
    ],
    name: "GreenBondReportAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "greenBondURI",
        type: "string",
      },
    ],
    name: "GrendBondEmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "couponDate_",
        type: "uint256",
      },
    ],
    name: "greenBondReports",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "greenBondURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "couponDate_",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "reportURI_",
        type: "string",
      },
    ],
    name: "submitGreenBondReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGreenBondMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IGreenBondMetadataInterface {
    return new Interface(_abi) as IGreenBondMetadataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGreenBondMetadata {
    return new Contract(address, _abi, runner) as unknown as IGreenBondMetadata;
  }
}
