/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ERC2771Context,
  ERC2771ContextInterface,
} from "../../../contracts/metatx/ERC2771Context";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102438061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063572b6c051461003b5780637da0a8771461006b575b600080fd5b61005560048036038101906100509190610180565b610089565b60405161006291906101c8565b60405180910390f35b61007361009b565b60405161008091906101f2565b60405180910390f35b6000610094826100c4565b9050919050565b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16149050919050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061014d82610122565b9050919050565b61015d81610142565b811461016857600080fd5b50565b60008135905061017a81610154565b92915050565b6000602082840312156101965761019561011d565b5b60006101a48482850161016b565b91505092915050565b60008115159050919050565b6101c2816101ad565b82525050565b60006020820190506101dd60008301846101b9565b92915050565b6101ec81610142565b82525050565b600060208201905061020760008301846101e3565b9291505056fea26469706673582212200297118bfb543bf39409de1ee86a31b60f8557a77d96c64ab8cee131869867ac64736f6c634300081b0033";

type ERC2771ContextConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC2771ContextConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC2771Context__factory extends ContractFactory {
  constructor(...args: ERC2771ContextConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ERC2771Context & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERC2771Context__factory {
    return super.connect(runner) as ERC2771Context__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextInterface {
    return new Interface(_abi) as ERC2771ContextInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC2771Context {
    return new Contract(address, _abi, runner) as unknown as ERC2771Context;
  }
}
