/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../../common";

export interface IGreenBondMetadataInternalInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "GreenBondReportAdded" | "GrendBondEmitted"
  ): EventFragment;
}

export namespace GreenBondReportAddedEvent {
  export type InputTuple = [couponDate: BigNumberish, reportURI: string];
  export type OutputTuple = [couponDate: bigint, reportURI: string];
  export interface OutputObject {
    couponDate: bigint;
    reportURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrendBondEmittedEvent {
  export type InputTuple = [greenBondURI: string];
  export type OutputTuple = [greenBondURI: string];
  export interface OutputObject {
    greenBondURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IGreenBondMetadataInternal extends BaseContract {
  connect(runner?: ContractRunner | null): IGreenBondMetadataInternal;
  waitForDeployment(): Promise<this>;

  interface: IGreenBondMetadataInternalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "GreenBondReportAdded"
  ): TypedContractEvent<
    GreenBondReportAddedEvent.InputTuple,
    GreenBondReportAddedEvent.OutputTuple,
    GreenBondReportAddedEvent.OutputObject
  >;
  getEvent(
    key: "GrendBondEmitted"
  ): TypedContractEvent<
    GrendBondEmittedEvent.InputTuple,
    GrendBondEmittedEvent.OutputTuple,
    GrendBondEmittedEvent.OutputObject
  >;

  filters: {
    "GreenBondReportAdded(uint256,string)": TypedContractEvent<
      GreenBondReportAddedEvent.InputTuple,
      GreenBondReportAddedEvent.OutputTuple,
      GreenBondReportAddedEvent.OutputObject
    >;
    GreenBondReportAdded: TypedContractEvent<
      GreenBondReportAddedEvent.InputTuple,
      GreenBondReportAddedEvent.OutputTuple,
      GreenBondReportAddedEvent.OutputObject
    >;

    "GrendBondEmitted(string)": TypedContractEvent<
      GrendBondEmittedEvent.InputTuple,
      GrendBondEmittedEvent.OutputTuple,
      GrendBondEmittedEvent.OutputObject
    >;
    GrendBondEmitted: TypedContractEvent<
      GrendBondEmittedEvent.InputTuple,
      GrendBondEmittedEvent.OutputTuple,
      GrendBondEmittedEvent.OutputObject
    >;
  };
}
