/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as greenPayoutSol from "./GreenPayout.sol";
export type { greenPayoutSol };
import type * as greenPayoutInternalSol from "./GreenPayoutInternal.sol";
export type { greenPayoutInternalSol };
import type * as iGreenPayoutSol from "./IGreenPayout.sol";
export type { iGreenPayoutSol };
import type * as iGreenPayoutInternalSol from "./IGreenPayoutInternal.sol";
export type { iGreenPayoutInternalSol };
